--TOPIC TEMPORARY TABLE

--CREATE TABLE #Temp_EMPLOYEE
--(EMPLOYEEID INT,
--JOBTITLE VARCHAR(100),
--SALARY INT
--)

--NOTE UNLIKE CTE WE DONT HAVE TO RUN IT EVERY TIME, IT JUST STORED AS TABLE

--SELECT *
--FROM #Temp_EMPLOYEE

--INSERT INTO #Temp_EMPLOYEE VALUES
--('1001', 'HR', '45000')

--INSERT INTO #Temp_EMPLOYEE
--SELECT *
--FROM [SQL TUTORIAL]..Employeesalary

--NOTE USE THIS TO DIRECTLY SELECT DATA FROM EXISTING TABLE AND NOW YOU CAN EXPERIMENT ON IT W/O AFFECTING ACTUAL TABLE
--NOTE- YOU CAN SKIP DBO PART BY JUST RIGHTING 2 DOTS


--CREATE TABLE #TEMP_EMPLOYEE2
--(JOBTITLE VARCHAR(50),
--EMPLOYEEPERJOB INT,
--AVGAGE INT,
--AVGSALARY INT)
--NOTE IF YOU RUN AGAIN IT WILL SHOW ERROR BCZ SOMEWHERE IS EXIST

DROP TABLE IF EXISTS #TEMP_EMPLOYEE2
CREATE TABLE #TEMP_EMPLOYEE2
(JOBTITLE VARCHAR(50),
EMPLOYEEPERJOB INT,
AVGAGE INT,
AVGSALARY INT)
--NOTE IF YOU RUN AGAIN IT WILL DROP PREVIOUS TABLE AND NO ERROR WILL COME PLUS NO DUPLICATION OF DATA


INSERT INTO #TEMP_EMPLOYEE2
SELECT JOBTITLE, COUNT(JOBTITLE), AVG(AGE), AVG(SALARY)
FROM [SQL TUTORIAL]..EMPLOYEEDEMOGRAPHICS AS EMP
JOIN [SQL TUTORIAL]..Employeesalary AS SAL
	ON EMP.EMPLOYEEID = SAL.EmployeeID
GROUP BY JOBTITLE

SELECT *
FROM #TEMP_EMPLOYEE2


