--TOPIC PARTITION BY

--SELECT *
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS

--SELECT *
--FROM [SQL TUTORIAL].DBO.Employeesalary

SELECT DEM.FIRSTNAME, DEM.LASTNAME, DEM.GENDER, SAL.SALARY, COUNT(GENDER) OVER (PARTITION BY GENDER) AS TOTALGENDER
FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS AS DEM
JOIN [SQL TUTORIAL].DBO.Employeesalary AS SAL
	ON DEM.EMPLOYEEID = SAL.EMPLOYEEID

				--VS

--SELECT DEM.GENDER, 	COUNT(GENDER) 
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS AS DEM
--JOIN [SQL TUTORIAL].DBO.Employeesalary AS SAL
--	ON DEM.EMPLOYEEID = SAL.EMPLOYEEID
--GROUP BY   DEM.GENDER