--SELECT TOP (1000) [EmployeeID]
--      ,[FirstName]
--      ,[LastName]
--      ,[Age]
--      ,[Gender]
--  FROM [SQL TUTORIAL].[dbo].[WareHouseEmployeeDemographics]


--SELECT FIRSTNAME, LASTNAME, AGE,
--CASE 
--	WHEN AGE > 30 THEN 'OLD'
--	ELSE 'YOUNG'
--END
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--WHERE AGE IS NOT NULL
--ORDER BY AGE

--SELECT FIRSTNAME, LASTNAME, AGE,
--CASE 
--	WHEN AGE > 30 THEN 'OLD'
--	WHEN AGE BETWEEN 27 AND 30 THEN 'YOUNG'
--	ELSE 'BABY'
--END
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--WHERE AGE IS NOT NULL
--ORDER BY AGE

--SELECT FIRSTNAME, LASTNAME, AGE,
--CASE 
--	WHEN AGE > 30 THEN 'OLD'
--	WHEN AGE = 38 THEN 'STANLEY'
--	ELSE 'BABY'
--END
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--WHERE AGE IS NOT NULL
--ORDER BY AGE
     --IN WHEN WE HAVE 2 CONDITION, BOTH CONDITION IS MET BY PERSON WITH AGE 38, BUT OUTPUT WILL ONLY FOLLOW 1ST CONDITION

SELECT FIRSTNAME, LASTNAME, JOBTITLE, SALARY,
CASE
	WHEN JOBTITLE = 'SALESMAN' THEN SALARY + (SALARY*.10)
	WHEN Jobtitle = 'ACCOUNTANT' THEN SALARY + (SALARY*.05)
	WHEN JOBTITLE = 'HR' THEN SALARY + (SALARY*.000001)
	ELSE SALARY + (SALARY * .3)
END
FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
JOIN [SQL TUTORIAL].DBO.Employeesalary
    ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID
