--TOPIC ALIASING

--SELECT FIRSTNAME + ' ' + LASTNAME AS FULLNAME
--FROM EMPLOYEEDEMOGRAPHICS

--SELECT DEMO.EMPLOYEEID
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS AS DEMO
--JOIN [SQL TUTORIAL].DBO.Employeesalary AS SAL
--	ON DEMO.EMPLOYEEID = SAL.EMPLOYEEID
	 
--	 NOTE ALWAYS USE TABLENAME.COLUMNNAME  IT WILL HELP WHEN THERE WILL BE MULTIPLE TABLES AND MULTIPLE COLUMN HAVING SAME NAME 

--SELECT DEMO.EMPLOYEEID, SAL.SALARY
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS AS DEMO
--JOIN [SQL TUTORIAL].DBO.Employeesalary AS SAL
--	ON DEMO.EMPLOYEEID = SAL.EMPLOYEEID

SELECT DEMO.EMPLOYEEID, DEMO.FIRSTNAME, SAL.Jobtitle, WARE.AGE
FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS AS DEMO
LEFT JOIN [SQL TUTORIAL].DBO.Employeesalary AS SAL
  ON DEMO.EMPLOYEEID = SAL.EmployeeID
LEFT JOIN [SQL TUTORIAL].DBO.WAREHOUSEEMPLOYEEDEMOGRAPHICS AS WARE
	ON DEMO.EMPLOYEEID = WARE.EMPLOYEEID

--SELECT *
--FROM [SQL TUTORIAL].DBO.WAREHOUSEEMPLOYEEDEMOGRAPHICS

