--SELECT JOBTITLE, COUNT(JOBTITLE)
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--JOIN [SQL TUTORIAL].DBO.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID

--GROUP BY JOBTITLE
--HAVING COUNT(JOBTITLE) > 1
--  NOTE - HAVING STATEMENT CAN'T BE USED BEFORE GROUP BY ORDER BCZ 1ST CREATE GROUP AND THEN IT COUNTS WHERE POSITION IS FILLED BY 
--			MORE THAN 1 PERSON 

--SELECT JOBTITLE, AVG(SALARY)
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--JOIN [SQL TUTORIAL].DBO.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID

--GROUP BY JOBTITLE
--HAVING AVG(SALARY) > 45000
--ORDER BY AVG(SALARY)

 --NOTE HAVING USE BEFORE ORDER BY- AFTER APPLYINH CONDITION IT WILL SET IN ORDER