--SELECT *
--FROM EMPLOYEEDEMOGRAPHICS

--Create Table WareHouseEmployeeDemographics 
--(EmployeeID int, 
--FirstName varchar(50), 
--LastName varchar(50), 
--Age int, 
--Gender varchar(50)
--)


--Insert into WareHouseEmployeeDemographics VALUES
--(1013, 'Darryl', 'Philbin', NULL, 'Male'),
--(1050, 'Roy', 'Anderson', 31, 'Male'),
--(1051, 'Hidetoshi', 'Hasagawa', 40, 'Male'),
--(1052, 'Val', 'Johnson', 31, 'Female')

--SELECT *
--FROM WAREHOUSEEMPLOYEEDEMOGRAPHICS

--SELECT *
--FROM EMPLOYEEDEMOGRAPHICS

--SELECT *
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--FULL OUTER JOIN [SQL TUTORIAL].[dbo].[WareHouseEmployeeDemographics]
--  ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = WAREHOUSEEMPLOYEEDEMOGRAPHICS.EMPLOYEEID



 

--SELECT *
--FROM EMPLOYEEDEMOGRAPHICS
--UNION
-- SELECT *
--FROM WAREHOUSEEMPLOYEEDEMOGRAPHICS
--  UNION REMOVE THE DUPLICATE AND AS BOTH TABLE HAVE SAME COLUMN NAME IT COMBINE BOTH OF THEM
    

--SELECT *
--FROM EMPLOYEEDEMOGRAPHICS
--UNION ALL
-- SELECT *
--FROM WAREHOUSEEMPLOYEEDEMOGRAPHICS
--ORDER BY EMPLOYEEID
    --UNION ALL KEEPS THE DUPLICATE ONE

--SELECT EMPLOYEEID, FIRSTNAME, AGE
--FROM EMPLOYEEDEMOGRAPHICS
--UNION 
-- SELECT EMPLOYEEID, JOBTITLE, Salary
--FROM Employeesalary
--ORDER BY EMPLOYEEID

--NOTE- WHILE USING UNION MAKE SURE THAT COLUMN YOU COMBINING FROM 2 TABLE IS SAME COLUMN TYPE
--     ABOVE EX FIRSTNAME <> JOBTITLE AND AGE <> SALARY