--SELECT TOP (1000) [EMPLOYEEID]
--      ,[FIRSTNAME]
--      ,[LASTNAME]
--      ,[AGE]
--      ,[GENDER]
--  FROM [SQL TUTORIAL].[dbo].[EMPLOYEEDEMOGRAPHICS]

--INSERT INTO EMPLOYEEDEMOGRAPHICS VALUES
--(1013, 'DARRYL', 'PHILBIN', NULL, 'MALE')

--INSERT INTO Employeesalary VALUES
--(1010, NULL, 47000),
--(NULL, 'SALESMAN', 43000)

--SELECT * 
--FROM EMPLOYEEDEMOGRAPHICS

--SELECT *
--FROM EMPLOYEESALARY

--SELECT *
--FROM [SQL TUTORIAL].dbo.EMPLOYEEDEMOGRAPHICS
--INNER JOIN [SQL TUTORIAL].dbo.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID
                             --TO COMBINE BOTH TABLE USING EMPLOYEE ID

--SELECT *
--FROM [SQL TUTORIAL].dbo.EMPLOYEEDEMOGRAPHICS
--FULL OUTER JOIN [SQL TUTORIAL].dbo.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID

--SELECT *
--FROM [SQL TUTORIAL].dbo.EMPLOYEEDEMOGRAPHICS
--RIGHT OUTER JOIN [SQL TUTORIAL].dbo.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID

--SELECT Employeesalary.EMPLOYEEID, FIRSTNAME, LASTNAME, JOBTITLE, SALARY
--FROM [SQL TUTORIAL].dbo.EMPLOYEEDEMOGRAPHICS
--LEFT OUTER JOIN [SQL TUTORIAL].dbo.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID

--SELECT EMPLOYEEDEMOGRAPHICS.EMPLOYEEID, FIRSTNAME, LASTNAME, SALARY
--FROM [SQL TUTORIAL].dbo.EMPLOYEEDEMOGRAPHICS
--INNER JOIN [SQL TUTORIAL].dbo.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID
--   WHERE FIRSTNAME <> 'MICHAEL'
--   ORDER BY SALARY DESC
                --USEING INNER JOIN TO FIND OUT DETAILS FROM 2 TABLE

--SELECT  JOBTITLE, AVG(SALARY)
--FROM [SQL TUTORIAL].dbo.EMPLOYEEDEMOGRAPHICS
--INNER JOIN [SQL TUTORIAL].dbo.Employeesalary
--   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID
--   WHERE JOBTITLE = 'SALESMAN'
--   GROUP BY JOBTITLE


SELECT  JOBTITLE, AVG(SALARY)
FROM [SQL TUTORIAL].dbo.EMPLOYEEDEMOGRAPHICS
INNER JOIN [SQL TUTORIAL].dbo.Employeesalary
   ON EMPLOYEEDEMOGRAPHICS.EMPLOYEEID = Employeesalary.EmployeeID
   WHERE JOBTITLE IN ('SALESMAN', 'ACCOUNTANT') 
   GROUP BY JOBTITLE