

--TOPIC - STORED PROCEDURE

--CREATE PROCEDURE TEST
--AS
--SELECT *
--FROM EMPLOYEEDEMOGRAPHICS


--EXEC TEST


--CREATE PROCEDURE TEMP_EMPLOYEE
--AS
--CREATE TABLE #TEMP_EMPLOYEE
--(JOBTITLE VARCHAR(50),
--EMPLOYEEPERJOB INT,
--AVGAGE INT,
--AVGSALARY INT)



--INSERT INTO #TEMP_EMPLOYEE
--SELECT JOBTITLE, COUNT(JOBTITLE), AVG(AGE), AVG(SALARY)
--FROM [SQL TUTORIAL]..EMPLOYEEDEMOGRAPHICS AS EMP
--JOIN [SQL TUTORIAL]..Employeesalary AS SAL
--	ON EMP.EMPLOYEEID = SAL.EmployeeID
--GROUP BY JOBTITLE

--SELECT *
--FROM #TEMP_EMPLOYEE

--EXEC TEMP_EMPLOYEE



CREATE PROCEDURE TEMP_EMPLOYEE
AS
CREATE TABLE #TEMP_EMPLOYEE
(JOBTITLE VARCHAR(50),
EMPLOYEEPERJOB INT,
AVGAGE INT,
AVGSALARY INT)



INSERT INTO #TEMP_EMPLOYEE
SELECT JOBTITLE, COUNT(JOBTITLE), AVG(AGE), AVG(SALARY)
FROM [SQL TUTORIAL]..EMPLOYEEDEMOGRAPHICS AS EMP
JOIN [SQL TUTORIAL]..Employeesalary AS SAL
	ON EMP.EMPLOYEEID = SAL.EmployeeID
GROUP BY JOBTITLE

SELECT *
FROM #TEMP_EMPLOYEE

EXEC TEMP_EMPLOYEE @JOBTITLE = 'SALESMAN'