

--STRING FUNCTION - TRIM, LTRM, RTRI, REPLACE, SUBSTRING, UPPER, LOWER

CREATE TABLE EmployeeErrors (
EmployeeID varchar(50)
,FirstName varchar(50)
,LastName varchar(50)
)

--Insert into EmployeeErrors Values 
--('1001  ', 'Jimbo', 'Halbert')
--,('  1002', 'Pamela', 'Beasely')
--,('1005', 'TOby', 'Flenderson - Fired')

Select *
From EmployeeErrors

--USING TRIM, LTRIM, RTRIM

SELECT EMPLOYEEID, TRIM(EMPLOYEEID) AS IDDTRIM
FROM EMPLOYEEERRORS

SELECT EMPLOYEEID, LTRIM(EMPLOYEEID) AS IDDTRIM
FROM EMPLOYEEERRORS

SELECT EMPLOYEEID, RTRIM(EMPLOYEEID) AS IDDTRIM
FROM EMPLOYEEERRORS

--USING REPLACE

SELECT LASTNAME, REPLACE(LASTNAME, '- FIRED', '') AS LASTNAEFIXED
FROM EMPLOYEEERRORS

--USING SUBSTRING


--NOTE - IT WILL SELECT FIRSTNAME COLUMN, IN THAT IT WILL START FROM 1ST CHARACTER, IN THAT SELECT NEXT 3 CHARACTERS
--SELECT SUBSTRING(FIRSTNAME,1,3) 
--FROM EMPLOYEEERRORS

--NOTE - IT WILL SELECT FIRSTNAME COLUMN, IN THAT IT WILL START FROM 3ST CHARACTER, IN THAT SELECT NEXT 3 CHARACTERS
--SELECT SUBSTRING(FIRSTNAME,3,3) 
--FROM EMPLOYEEERRORS

SELECT ERR.FIRSTNAME, DEM.FIRSTNAME
FROM EMPLOYEEERRORS AS ERR
JOIN EMPLOYEEDEMOGRAPHICS AS DEM
	ON ERR.FIRSTNAME = DEM.FIRSTNAME
--NOTE- ONLY WORK ON TOBY BCZ IT IS COMMON

SELECT ERR.FIRSTNAME, SUBSTRING(ERR.FIRSTNAME,1,3), DEM.FIRSTNAME, SUBSTRING(DEM.FIRSTNAME,1,3)
FROM EMPLOYEEERRORS AS ERR
JOIN EMPLOYEEDEMOGRAPHICS AS DEM
	ON SUBSTRING(ERR.FIRSTNAME,1,3) = SUBSTRING(DEM.FIRSTNAME,1,3)
--NOTE- IT WILL ONLY TRY TO MATCH 1ST 3 CHARACTER ON BOTH TABLES AND THAT WILL BE THE SAME
--NOTE- IT WILL HELP BCZ PEOPLES NAME'S STARTING CHARACTER WILL MATCH BCZ SO MANY USE SHORT NAME INSTEAD OF LONG


--TO USE LAST 3 CHARACTER, 

SELECT REVERSE(SUBSTRING(REVERSE(FIRSTNAME),1,3))
FROM EMPLOYEEERRORS



--USING UPPER AND LOWER

SELECT FIRSTNAME, LOWER(FIRSTNAME)
FROM EMPLOYEEERRORS

SELECT FIRSTNAME, UPPER(FIRSTNAME)
FROM EMPLOYEEERRORS