--UPDATING/DELETING

--SELECT *
--FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS

--UPDATE [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--SET EMPLOYEEID = 1012
--WHERE FIRSTNAME = 'HOLY' AND LASTNAME = 'FLAX'


SELECT *
FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS

--UPDATE [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--SET AGE = 31, GENDER = 'FEMALE'
--WHERE FIRSTNAME = 'HOLY' AND LASTNAME = 'FLAX'
--		OR USE WHERE EMPLOYEEID = 1012


--DELETE FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS
--WHERE EMPLOYEEID = 1005
--     NOTE USE SELECT EMPLOYEEID = 1005 BEFORE DELETING BCZ THAT WAY YOU CAN SEE THAT WHAT YOU ARE GOINH TO DELETE