--TOPIC CTEs


WITH CTE_EMPLOYEE AS 
(SELECT FIRSTNAME, LASTNAME, GENDER, SALARY
, COUNT(GENDER) OVER (PARTITION BY GENDER) AS TOTALGENDER
, AVG(SALARY) OVER (PARTITION BY GENDER) AS AVGSALARY
FROM [SQL TUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS AS EMP
JOIN [SQL TUTORIAL].DBO.EMPLOYEESALARY AS SAL
	ON EMP.EMPLOYEEID = SAL.EMPLOYEEID
WHERE SALARY > 45000
)
--SELECT FIRSTNAME, AVGSALARY
SELECT *
FROM CTE_EMPLOYEE

--NOTE WE ARE CREATING CTE_EMPLOYEE TABLE WITH GIVEN CONDITION AND NOW CAN RUN EVERYTHING ON THAT SPECIFIC TABLE ONLY
--NOTE - IT IS NOT STORING CTE-EMPLOYE TABLE LIKE PREVIOUS ONES IT CREATE CTE TABLE EVERYTIE WE RUN THE PROGRAM
--NOTE - USE SELECT STATEMENT RIGHT AFTER THE CTE QUERY OTHERWISE NOT WORK

--PARTITION BY - EX TO GET AVG SALARY BUT FOR BOTH LIKE MALE AVG SALARY AND FEMALE AVG SALARY, SO WE USE PARTITION BY GENDER
-- AND THEN OVER IT WE USE AVG SALARY